# Generated by Django 4.1.7 on 2023-05-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article_or_news',
            new_name='categoryType',
        ),
    ]
