# Generated by Django 4.1.7 on 2023-07-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_rename_article_or_news_post_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('ART', 'statya'), ('NWS', 'HoBocTb')], default='ART', max_length=3),
        ),
    ]
